### PR TITLE
warning is thrown on unknown action instead of error

### LINKED ISSUE #7: An unknown action should not prevent the request from executing
If there is an unknown action in the system (e.g. there is an application content that refers to an unknown action class), and an odata response contains the list of available actions (which is the default), it will result in the following error (500 internal server eror):

`InvalidContentActionException: Unknown action.`

The operation (e.g. a content creation) may execute correctly, but the response is messed up with this error result because of the missing action. This should be a simple _warning_ in the log.

The exception is thrown by the _ActionFramework.GetActions_ method.

### PR DESCRIPTION
**Pull request by iviczl**
This closes #7

### CODE REVIEW

File: src/ContentRepository/ApplicationModel/ActionFramework.cs [hunk 1]
```diff
@@ -205,7 +206,19 @@ private static ActionBase CreateActionWithPermissions(Application app, Content c
...
+            {
+                action = app.CreateAction(context, backUri, parameters);
+            }
+            catch (InvalidContentActionException ex)
+            {
+                if (ex.Reason != InvalidContentActionReason.UnknownAction)
+                {
+                   throw;
+                }
+                SnLog.WriteWarning("Application content refers to an unknown action class.", EventId.ActionFramework);
```
Comment (tusmester) [inline src/ContentRepository/ApplicationModel/ActionFramework.cs]: Please include the app path and the invalid action type name in the message.

Comment (iviczl) [inline src/ContentRepository/ApplicationModel/ActionFramework.cs]: check it now, it will serve as well as you defined.
